name: Run CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  TZ: Asia/Singapore
  NODE_OPTIONS: --max_old_space_size=8192
  GENERATE_SOURCEMAP: false

jobs:
  deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repository
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: |
          JOBS=$(nproc) yarn install --frozen-lockfile
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
  compile:
    name: Compile
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: yarn run tsc
  format_ci:
    name:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: yarn run format:ci
  eslint:
    name: Eslint
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: yarn run eslint
  build:
    name: Build
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: yarn run build
  coveralls:
    name: Check code coverage
    needs: [deps, compile, format_ci, eslint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - name: Coveralls
        run: yarn run test-coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
